In [89]:
import pandas as pd
import cleaning



df1 = pd.read_csv('sneakers_adidas.csv')
df2 = pd.read_csv('sneakers_jordan.csv')
df3 = pd.read_csv('sneakers_nike.csv')
df4 = pd.read_csv('sneakers_puma.csv')
df5 = pd.read_csv('sneakers_mizuno.csv')

In [90]:
api_df = pd.concat([df1, df2, df3, df4], ignore_index = True)

api_df.shape

(400, 14)

In [91]:
df5.shape

(56, 7)

In [92]:
api_df.head()

,id,brand,colorway,estimatedMarketValue,gender,image,links,name,releaseDate,releaseYear,retailPrice,silhouette,sku,story
0,cc25575e-b235-46bc-b12e-6a66633c3ddf,adidas,Core Black/Cloud White/Chalk White,131,men,"{'360': [], 'original': 'https://image.goat.co...",{'stockX': 'https://stockx.com/adidas-crazy-ii...,adidas Crazy IIInfinity Stormtrooper,2024-12-30,2024,160,Crazy IIInfinity,IG6303,The adidas Crazy IIInfinity ‘Stormtrooper’ pre...
1,be58449f-1866-46c7-93ba-4b4db96cb291,adidas,Off-White/Black/Metallic Gold,155,men,"{'360': [], 'original': 'https://image.goat.co...",{'stockX': 'https://stockx.com/adidas-harden-v...,adidas Harden Vol. 7 Year of the Dragon (2024),2024-12-29,2024,160,Harden Vol. 7,IH7516,NaN
2,7bd701b1-9c21-4c1a-9569-4165b9df529c,adidas,Core White/Matte Gold/Halo Gold,96,men,"{'360': [], 'original': 'https://image.goat.co...",{'stockX': 'https://stockx.com/adidas-don-issu...,adidas D.O.N. Issue #5 Year of the Dragon (2024),2024-12-27,2024,120,D.O.N. Issue #5,IH7517,NaN
3,8682e7bd-a1bb-4552-813a-2c469c23e27d,adidas,Crystal White/Cloud White/Better Scarlet,204,men,"{'360': [], 'original': 'https://image.goat.co...",{'stockX': 'https://stockx.com/adidas-nmd-r1-c...,adidas NMD R1 Crystal White Better Scarlet,2024-11-26,2024,130,NMD Runner,IF3501,NaN
4,255eef3c-e8d7-4418-b14b-3d3edc4c3beb,adidas,Black/Carbon/Lucid Lemon,133,men,"{'360': [], 'original': 'https://image.goat.co...",{'stockX': 'https://stockx.com/adidas-ae-1-sto...,adidas AE 1 Stormtrooper,2024-03-01,2024,120,AE 1,IF1857,NaN

In [93]:
columns_to_drop = ['id', 'image', 'links', 'releaseDate', 'releaseYear', 'sku', 'story']
api_df = cleaning.drop_columns(api_df, columns_to_drop)
api_df

,brand,colorway,estimatedMarketValue,gender,name,retailPrice,silhouette
0,adidas,Core Black/Cloud White/Chalk White,131,men,adidas Crazy IIInfinity Stormtrooper,160,Crazy IIInfinity
1,adidas,Off-White/Black/Metallic Gold,155,men,adidas Harden Vol. 7 Year of the Dragon (2024),160,Harden Vol. 7
2,adidas,Core White/Matte Gold/Halo Gold,96,men,adidas D.O.N. Issue #5 Year of the Dragon (2024),120,D.O.N. Issue #5
3,adidas,Crystal White/Cloud White/Better Scarlet,204,men,adidas NMD R1 Crystal White Better Scarlet,130,NMD Runner
4,adidas,Black/Carbon/Lucid Lemon,133,men,adidas AE 1 Stormtrooper,120,AE 1
...,...,...,...,...,...,...,...
395,Puma,For All Time Red/Black,45,infant,Kruz Infant 'For All Time Red',45,Kruz Nitro
396,Puma,White/Turquoise Surf,75,youth,Cali Court Match Big Kid 'White Turquoise Surf',75,Cali
397,Puma,White/Warm White,75,youth,Cali Court Match Big Kid 'Hearts',75,Cali
398,Puma,Black/White,45,infant,Kruz Infant 'Black White',45,Kruz Nitro
399,Puma,White/Pink Lilac,75,youth,Cali Court Match Big Kid 'White Pink Lilac',75,Cali

In [94]:
api_df = api_df.rename(columns = {'colorway' : 'primary_color'})
api_df['primary_color'] = api_df['primary_color'].str.split('/').str[0]
api_df['primary_color'].nunique()

130

In [95]:
df5 = df5[df5['primary_color'] != 'Lightning Star Jr']
df5 = df5[df5['primary_color'] != 'Wos']
df5['primary_color'].unique()

array(['Preto', 'Branca', 'Preta', 'Azul', 'Amarelo', 'Roxo', 'Rosa',
       'Laranja', 'Branco', 'Br', 'Bo', 'Cinza'], dtype=object)

In [96]:
color_changes = {'Preto':'Black',
                 'Preta':'Black',
                 'Branca':'White',
                 'Branco':'White',
                 'Azul':'Blue',
                 'Amarelo':'Yellow',
                 'Roxo':'Purple',
                 'Br':'White',
                 'Rosa':'Pink',
                 'Bo':'Burgundy',
                 'Laranja':'Orange',
                 'Cinza':'Grey'
                 }
df5['primary_color'] = df5['primary_color'].replace(color_changes)
df5['primary_color'].unique()

df5

,brand,primary_color,estimatedMarketValue,gender,name,retailPrice,silhouette
0,Mizuno,Black,244.99,men,Botas Futebol Mizuno Morelia Neo Beta Japan,349.99,Mizuno Morelia
1,Mizuno,White,251.99,men,Botas Futebol Mizuno Morelia Neo Japan Mix,359.99,Mizuno Morelia
2,Mizuno,Black,22.49,Another_One,Calńa Mizuno Core,24.99,Core
3,Mizuno,Blue,14.39,Another_One,Joelheira Mizuno,15.99,Joelheira
4,Mizuno,Black,26.99,Another_One,Joelheira Mizuno,29.99,Joelheira
5,Mizuno,Blue,26.99,Another_One,Joelheira Mizuno,29.99,Joelheira
6,Mizuno,White,26.99,Another_One,Joelheira Mizuno,29.99,Joelheira
7,Mizuno,White,7.19,Another_One,Meias Mizuno,7.99,Meias
8,Mizuno,White,10.79,Another_One,Meias de Volei,11.99,Meias
9,Mizuno,White,12.15,Another_One,Meias De Volei Mizuno s,13.50,Meias
10,Mizuno,Black,6.29,Another_One,Meias Volei,6.99,Meias
11,Mizuno,Yellow,52.50,men,Tenis Running Mizuno Wave Polaris,104.99,Wave
13,Mizuno,Purple,52.50,men,Tenis Running Mizuno Wave Polaris Sr,104.99,Wave
14,Mizuno,Blue,35.00,kid,Tenis Running Wave Rider Jr,69.99,Wave
15,Mizuno,Pink,35.00,kid,Tenis Running Wave Rider Jr,69.99,Wave
16,Mizuno,Blue,85.00,men,Teni Bota Volei Mizuno Shoe Wave Lightning Z,169.99,Wave
17,Mizuno,Orange,125.99,men,Tenis Volei Mizuno Wave Lightning Neo,179.99,Wave
18,Mizuno,White,80.99,men,Teni Bota Volei Mizuno Thunder,89.99,Wave
19,Mizuno,Blue,90.00,men,Teni Volei Mizuno Wave Momentum,179.99,Thunder
20,Mizuno,White,111.99,men,Tenis Bota Volei Wave Lightning Z,159.99,Wave
21,Mizuno,Black,90.00,men,Tenis Volei Mizuno Shoe Wave Lightning Neoz,179.99,Wave
22,Mizuno,Blue,80.00,men,Teni Bota Volei Mizuno Shoe Wave Lightning,159.99,Wave
23,Mizuno,Blue,85.00,men,Teni Bota Volei Mizuno Wave Momentum,169.99,Wave
24,Mizuno,White,80.00,men,Tenis Andebol Mizuno Wave Stealth,159.99,Wave
25,Mizuno,Blue,60.00,men,Tenis Volei Mizuno Shoe Wave Voltage,119.99,Wave
26,Mizuno,Blue,80.00,men,Tenis Mizuno Shoe Wave Momentun,159.99,Wave
27,Mizuno,White,152.99,men,Teni Bota Volei Mizuno Wave Lightning Z8,169.99,Wave
28,Mizuno,White,62.99,men,Teni Bota Volei Mizuno Thunder Blade Z,89.99,Wave
29,Mizuno,Black,85.00,men,Teni Bota Volei Mizuno Wave Momentum,169.99,Thunder
30,Mizuno,Blue,80.00,men,Tenis Andebol Mizuno Wave Stealth,159.99,Wave
31,Mizuno,White,75.00,men,Tenis Andebol Mizuno Wave,149.99,Wave
32,Mizuno,White,75.00,men,Tenis Andebol Mizuno Wave Stealth Neo,149.99,Wave
33,Mizuno,Blue,75.00,men,Tenis Padel Mizuno,149.99,Wave
34,Mizuno,Black,60.00,men,Tenis Padel Mizuno Wave Exceed Light,119.99,Padel
35,Mizuno,Black,55.00,women,Tenis Padel Mizuno Wave Exceed,109.99,Wave
36,Mizuno,White,76.99,men,Tenis Andebol Mizuno Wave Dimension,109.99,Wave
37,Mizuno,Burgundy,75.00,men,Tenis Andebol Mizuno Wave Stealth Neo,149.99,Wave
38,Mizuno,Grey,75.00,men,Tenis Andebol Mizuno Wave Stealth Neo,149.99,Wave
39,Mizuno,Blue,35.00,men,Tenis Andebol Mizuno Lighting Star,69.99,Wave
40,Mizuno,Black,40.00,men,Teni Bota Andebol Mizuno Thunder Blade,79.99,Thunder
41,Mizuno,Blue,67.50,men,Tenis Volei Mizuno Wave Luminous 2,134.99,Wave
42,Mizuno,White,104.99,men,Tenis Volei Wave Lightning Z,149.99,Wave
43,Mizuno,Grey,60.00,men,Tenis Volei Mizuno Shoe Voltage,119.99,Voltage
44,Mizuno,White,55.99,men,Tenis Volei Thunder Blade Z,79.99,Thunder
45,Mizuno,Blue,77.50,men,Tenis Volei Mizuno Wave Momentum 2,154.99,Wave
47,Mizuno,Blue,62.99,men,Teni Bota Volei Mizuno Thunder Blade Z,89.99,Thunder
48,Mizuno,Black,13.49,Another_One,Manguito Mizuno,14.99,Manguito
49,Mizuno,Black,13.49,Another_One,Manguito Asics,14.99,Manguito
50,Mizuno,White,13.49,Another_One,Manguito Mizuno,14.99,Manguito
51,Mizuno,Black,17.99,Another_One,Calńao Mizuno,19.99,Perneira
52,Mizuno,Black,14.39,Another_One,Calńao De Volei,15.99,Calçao
53,Mizuno,Blue,14.39,Another_One,Calńao De Volei,15.99,Calçao
54,Mizuno,Black,10.79,Another_One,Perneira Mizuno Compression,11.99,Calçao
55,Mizuno,Black,22.49,Another_One,Meia CompressŃo Mizuno,24.99,Meia

In [97]:
df = pd.concat([api_df, df5], ignore_index = True)
df

,brand,primary_color,estimatedMarketValue,gender,name,retailPrice,silhouette
0,adidas,Core Black,131.00,men,adidas Crazy IIInfinity Stormtrooper,160.00,Crazy IIInfinity
1,adidas,Off-White,155.00,men,adidas Harden Vol. 7 Year of the Dragon (2024),160.00,Harden Vol. 7
2,adidas,Core White,96.00,men,adidas D.O.N. Issue #5 Year of the Dragon (2024),120.00,D.O.N. Issue #5
3,adidas,Crystal White,204.00,men,adidas NMD R1 Crystal White Better Scarlet,130.00,NMD Runner
4,adidas,Black,133.00,men,adidas AE 1 Stormtrooper,120.00,AE 1
...,...,...,...,...,...,...,...
449,Mizuno,Black,17.99,Another_One,Calńao Mizuno,19.99,Perneira
450,Mizuno,Black,14.39,Another_One,Calńao De Volei,15.99,Calçao
451,Mizuno,Blue,14.39,Another_One,Calńao De Volei,15.99,Calçao
452,Mizuno,Black,10.79,Another_One,Perneira Mizuno Compression,11.99,Calçao
453,Mizuno,Black,22.49,Another_One,Meia CompressŃo Mizuno,24.99,Meia

In [98]:
cleaning.standardize_column_names(df)
df

,brand,primary_color,estimatedmarketvalue,gender,name,retailprice,silhouette
0,adidas,Core Black,131.00,men,adidas Crazy IIInfinity Stormtrooper,160.00,Crazy IIInfinity
1,adidas,Off-White,155.00,men,adidas Harden Vol. 7 Year of the Dragon (2024),160.00,Harden Vol. 7
2,adidas,Core White,96.00,men,adidas D.O.N. Issue #5 Year of the Dragon (2024),120.00,D.O.N. Issue #5
3,adidas,Crystal White,204.00,men,adidas NMD R1 Crystal White Better Scarlet,130.00,NMD Runner
4,adidas,Black,133.00,men,adidas AE 1 Stormtrooper,120.00,AE 1
...,...,...,...,...,...,...,...
449,Mizuno,Black,17.99,Another_One,Calńao Mizuno,19.99,Perneira
450,Mizuno,Black,14.39,Another_One,Calńao De Volei,15.99,Calçao
451,Mizuno,Blue,14.39,Another_One,Calńao De Volei,15.99,Calçao
452,Mizuno,Black,10.79,Another_One,Perneira Mizuno Compression,11.99,Calçao
453,Mizuno,Black,22.49,Another_One,Meia CompressŃo Mizuno,24.99,Meia

In [99]:
cleaning.unique_values_for_categorical(df, 30)

brand uniques: ['adidas' 'Jordan' 'Nike' 'Puma' 'Mizuno']
primary_color uniques: more than 30 values
gender uniques: ['men' 'child' 'women' 'youth' 'infant' 'toddler' 'preschool'
 'Another_One' 'kid']
name uniques: more than 30 values
silhouette uniques: more than 30 values

In [100]:
df = df[df['gender'] != 'Another_One']

In [101]:
replacement_dict = {'child': 'kid', 'youth': 'kid', 'infant': 'kid', 'toddler': 'kid', 'preschool': 'kid'}
df['gender'] = df['gender'].replace(replacement_dict)
df['gender'].unique()

C:\Users\erik\AppData\Local\Temp\ipykernel_51364\4175854290.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['gender'] = df['gender'].replace(replacement_dict)

array(['men', 'kid', 'women'], dtype=object)

In [102]:
df.to_csv('sneakers.csv', index=False)